---
repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        name: black
        args: ["--config", "pyproject.toml"]
  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0
    hooks:
      - id: pydocstyle
        name: pydocstyle
        args: ["--config=pyproject.toml"]
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.39.0
    hooks:
      - id: markdownlint
        args: ["-c", ".markdownlint.json"]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.35.1
    hooks:
      - id: yamllint
        args: ["-c", ".yamllint.yml"]
  - repo: local
    hooks:
      - id: import-guard
        name: import-guard
        entry: python scripts/check_imports.py
        language: system
        types: [python]
